FROM rust:1.92-bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libclang-dev \
    libprotobuf-dev \
    protobuf-compiler \
    musl-tools \
    libseccomp-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /workspace
