FROM rust:1.92-bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libclang-dev \
    libprotobuf-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
